serviceId: "deployer"
logfile: "dpeloyer.log"
initialiser: "20.219.74.29:5003"
mongo:
  address: "mongodb+srv://mongo2mongo:test123@cluster0.7ik1k.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
  db:   "node_manager_db"
  collection: "app_deployment_metadata"

kafka:
  address: ["52.172.89.249:9092"]
