serviceId: "scheduler"
initialiser:  "127.0.0.1:5003"
node_manager:
  _id: "624afd50c2a6e828c5ea472e" 
mongo:
  address: "mongodb+srv://mongo2mongo:test123@cluster0.7ik1k.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
  db:  "scheduler_db"
  collection:  "scheduler_metadata"
  collection_1: "schedulable_app_metadata"
kafka:
  group: 'test-consumer-group'
  address: ['52.172.25.250:9092']
  topic: "scheduler"
cron:
  user: "vishal"
